# Generated by Django 5.1.1 on 2024-10-14 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='date publication')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='resume')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_memories', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='file_memories/', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='date publication')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='resume')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_thesis', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='file_thesis/', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_commentaire', models.DateTimeField(auto_now_add=True, verbose_name='date_commentaire')),
                ('object_id', models.PositiveIntegerField(verbose_name='object_id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='fonction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_academic', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='domain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, verbose_name='matricule')),
                ('promotion', models.CharField(max_length=255, verbose_name='promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
