# Generated by Django 5.1.1 on 2024-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('fist_name', models.CharField(max_length=255, verbose_name='first_name')),
                ('is_student', models.BooleanField(default=False, verbose_name='is student')),
                ('is_personal_academic', models.BooleanField(default=False, verbose_name='is personal academic')),
                ('is_searcher', models.BooleanField(default=False, verbose_name='is searcher')),
            ],
        ),
    ]
