# Generated by Django 5.1.1 on 2024-10-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fist_name_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='app.author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='app.author', verbose_name='author'),
        ),
    ]
