# Generated by Django 5.1.1 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_memory_author_alter_thesis_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='prouve',
            field=models.BooleanField(default=False, verbose_name='prouve'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='prouve',
            field=models.BooleanField(default=False, verbose_name='prouve'),
        ),
    ]
