# Generated by Django 5.1.1 on 2024-10-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_commentaire_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_commentaire']},
        ),
        migrations.AlterField(
            model_name='memory',
            name='date_publication',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date publication'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_publication',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date publication'),
        ),
    ]
