# Generated by Django 5.1.1 on 2024-10-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-date_publication']},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ['-date_publication']},
        ),
    ]
